version: "3"

# image今latestタグを使っているが、commitのsha1をタグとして使うようにして、それを環境変数で読むようにしたい。
# todo: circle ciで二つのイメージをecrにアップさせる。
# todo: 環境変数を使ってlatestではなく、sha1を見させるように変更
services:
  app:
    image: 882275384674.dkr.ecr.ap-northeast-1.amazonaws.com/connpass-map-api-app:latest
    ports:
      - 7777:7777
  nginx:
    image: 882275384674.dkr.ecr.ap-northeast-1.amazonaws.com/connpass-map-api_nginx:latest
    ports:
      - 80:80
    depends_on:
      - app
