version: "3"

services:
  app:
    image: "882275384674.dkr.ecr.ap-northeast-1.amazonaws.com/connpass-map-api-app:${SHA1}"
    environment:
      - API_VERSION="${SHA1}"
    ports:
      - 7777:7777
  nginx:
    image: "882275384674.dkr.ecr.ap-northeast-1.amazonaws.com/connpass-map-api-nginx:${SHA1}"
    ports:
      - 80:80
    depends_on:
      - app
