version: "3.5"

services:
  app:
    build:
      context: .
      target: builder
    volumes:
      - ./:/app
    command: realize start --server
    ports:
      - 7777:7777
  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - app
