version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@0.0.2

executors:
  default:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/pokotyan/connpass-map-api

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          name: Restore go modules cache
          keys:
            - go-modules-cache-v1-{{ checksum "go.sum" }}

      - run: go mod download

      - save_cache:
          name: Save go modules cache
          key: go-modules-cache-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - setup_remote_docker
      - run: docker build -t connpass-map-api .

  lint:
    executor:
      name: default
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: golint ./...

workflows:
  build_and_push:
    jobs:
      - build
      - lint
      - aws-ecr/build_and_push_image:
          requires:
            - build
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "connpass-map-api"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - /feature.*/
                - master
