version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.5.0
executors:
  default:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/pokotyan/connpass-map-api
jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          name: Restore go modules cache
          keys:
            - go-modules-cache-v1-{{ checksum "go.sum" }}

      - run: go mod download

      - save_cache:
          name: Save go modules cache
          key: go-modules-cache-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - setup_remote_docker
      - run: docker build -t connpass-map-api .
      - run: docker build -t connpass-map-api_nginx ./nginx
  lint:
    executor:
      name: default
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: golint ./...
  # aws-ecr/build-and-push-image:
  #   parameters:
  #     aws-access-key-id:
  #       type: env_var_name
  #       default: AWS_ACCESS_KEY_ID
  #     aws-secret-access-key:
  #       type: env_var_name
  #       default: AWS_SECRET_ACCESS_KEY
  #     account-url:
  #       type: env_var_name
  #       default: AWS_ECR_ACCOUNT_URL
  #     region:
  #       type: env_var_name
  #       default: AWS_REGION
workflows:
  build_and_push:
    jobs:
      - build
      - lint
      - aws-ecr/build-and-push-image:
          requires:
            - build
          account-url: ${AWS_ECR_ACCOUNT_URL}
          repo: "connpass-map-api-app"
          region: ${AWS_REGION}
          tag: latest
          path: .
          filters:
            branches:
              only:
                - /feature.*/
                - master
      - aws-ecr/build-and-push-image:
          requires:
            - build
          account-url: ${AWS_ECR_ACCOUNT_URL}
          repo: "connpass-map-api-nginx"
          region: ${AWS_REGION}
          tag: latest
          path: ./nginx
          filters:
            branches:
              only:
                - /feature.*/
                - master
