version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/pokotyan/connpass-map-api
    steps:
      - checkout
      - run: go mod download

workflows:
  build_and_push:
    jobs:
      - build
      - aws-ecr/build_and_push_image:
          requires:
            - build
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "connpass-map-api"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - /feature.*/
                - master
